sudo: required
services:
  - docker

before_install:
  - docker build -t roronoazoro9695/docker-react-secondary -f Dockerfile.dev .

script:
  - docker run -e CI=true roronoazoro9695/docker-react-secondary npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react-secondary"
  env: "docker-react-secondary-env"
  bucket_name: "elasticbeanstalk-ap-south-1-839117473964"
  bucket_path: "docker-react-secondary"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"